HairSalon/Models/Client.cs
using System.Collections.Generic;
using System;

namespace HairSalon.Models
{
  public class Client 
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public DateTime AppointmentDate { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist 
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Specialty { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(client => client.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {

        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet("/Gallery")]
        public ActionResult Gallery()
        {
            return View();
        }
    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {

    
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      
      
   
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4 class="stylistLink">Add new client to the roster</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.AppointmentDate)
  @Html.TextBoxFor(model => model.AppointmentDate, "{0:d MMM yyyy}", new { @class="input-large", type = "datetime-local" })

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Add new client and appointment" class="btn btn-default" />
}
<p class="bodyLink">@Html.ActionLink("Show all clients", "Index")</p>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Are you sure you want to remove this client?</h2>

<p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
<p class="bodyLink">@Html.ActionLink("Back to clients", "Index")</p>

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Client Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.AppointmentDate): @Html.DisplayFor(model => model.AppointmentDate)<h3>
<p class="bodyLink">@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId })</p>
<p class="bodyLink">@Html.ActionLink("Remove Client", "Delete", new { id = Model.ClientId })</p>
<p class="bodyLink">@Html.ActionLink("Back to clients", "Index")</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Edit</h2>

<h4>Edit client details: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ClientId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.AppointmentDate)
  @Html.EditorFor(model => model.AppointmentDate)

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Save" />
}

<p class="bodyLink">@Html.ActionLink("Back to clients", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>This stylist currently does not have any clients!</h3>
} 

@foreach (Client client in Model)
{
  <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
}

<p class="bodyLink">@Html.ActionLink("Add new client", "Create")</p>

HairSalon/Views/Home/Gallery.cshtml
@{
  Layout = "_Layout";
}

<h1>Gallery of our stylists' work coming soon!!! Stay tuned...</h1>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<div class="text-center">
    <h1 class="display-4">Stylists and Clients Manager</h1>
    <p class="bodyLink">@Html.ActionLink("See all stylists", "Index", "Stylists")</p>
    <p class="bodyLink">@Html.ActionLink("See all clients", "Index", "Clients")</p> 
</div>

HairSalon/Views/Shared/Footer.cshtml
<div id="footer">© LouBear Mechanations 2022</div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HairSalon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HairSalon.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-scissors"></i> Eau Cl-hair's Beauty Salon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-even">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <p>@Html.ActionLink("Home", "Index", "Home")</p>
                        </li>
                        <li class="nav-item">
                            <p>@Html.ActionLink("Gallery", "Gallery", "Home")</p>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <img src="https://images.unsplash.com/photo-1587115508501-2628609cbea6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="scissorsPic">
            @await Html.PartialAsync("Footer")
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h3>Add a new stylist</h3>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Specialty)
  @Html.TextBoxFor(model => model.Specialty)
  <input type="submit" value="Add new stylist" />
}
<p class="bodyLink">@Html.ActionLink("Show all stylists", "Index")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Are you sure you want to remove stylist from system?</h2>

<p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
<p class="bodyLink">@Html.ActionLink("Back to stylists", "Index")</p>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Stylist Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Specialty): @Html.DisplayFor(model => model.Specialty)<h3>
<p class="bodyLink">@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId })</p>
<p class="bodyLink">@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId })</p>
<p class="bodyLink">@Html.ActionLink("Back to Stylists", "Index")</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Edit</h2>

<h4>Edit this stylist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Specialty)
  @Html.EditorFor(model => model.Specialty)

  <input type="submit" value="Save" />
}
<p class="bodyLink">@Html.ActionLink("Back to stylists", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No stylists have been added yet!</h3>
} 

<ul>
  @foreach(Stylist stylist in Model)
  {
    <li class="stylistLink">@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
  }
</ul>

<p class="bodyLink">@Html.ActionLink("Add new stylist", "Create")</p>
<p class="bodyLink">@Html.ActionLink("Home", "Index", "Home")</p>